version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: devsecops-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendamento_consultas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # --- FIX DE SEGURANÇA SEMGREP ---
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/run/postgresql
      - /tmp
    # ---------------------------------
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agendamento_consultas"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devsecops-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecops-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    # --- FIX DE SEGURANÇA SEMGREP ---
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    # ---------------------------------
    networks:
      - devsecops-net

  localstack:
    image: localstack/localstack:3.0.0
    container_name: devsecops-localstack
    ports:
      - "4566:4566" # Porta Gateway unificada do LocalStack
    environment:
      - SERVICES=s3,ec2,sqs,sns,cloudwatch,logs,iam,sts,kms
      - DEBUG=0
    volumes:
      - localstack_data:/var/lib/localstack
      # nosemgrep: yaml.docker-compose.security.docker-sock-mount
      - /var/run/docker.sock:/var/run/docker.sock
    # --- FIX DE SEGURANÇA SEMGREP ---
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/lib/localstack/cache
    # ---------------------------------
    networks:
      - devsecops-net

volumes:
  postgres_data:
  localstack_data:

networks:
  devsecops-net:
    driver: bridge
    
